sudo: required

language: python
python: 3.5

services:
- docker

env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27

before_install:
- docker pull neo4j
- docker run -d -p 127.0.0.1:7474:7474 -p 127.0.0.1:7687:7687 --env 'NEO4J_AUTH=neo4j/admin' neo4j
- docker ps -a

install: pip install -U tox

script: tox -e ${TOXENV}
