version: '2'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    links:
      - graph
    environment:
      - TOXENV
  graph:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/admin
